server:
  port: 8000

spring:
  application:
    name: apigateway
  config:
    import: optional:configserver:http://localhost:8888
  cloud:
    gateway:
      routes:
        #user-service
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user-service/**
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/user-service/(?<segment>.*), /$\{segment}
        - id: asset-service
          uri: lb://ASSET-SERVICE
          predicates:
            - Path=/asset-service/**
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/asset-service/(?<segment>.*), /$\{segment}
        - id: post-service
          uri: lb://POST-SERVICE
          predicates:
            - Path=/post-service/**
          filters:
            - RewritePath=/post-service/(?<segment>.*), /$\{segment}
        - id: store-service
          uri: lb://STORE-SERVICE
          predicates:
            - Path=/store-service/**
          filters:
            - RewritePath=/store-service/(?<segment>.*), /$\{segment}
        - id: order-service
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/order-service/**
          filters:
            - RewritePath=/order-service/(?<segment>.*), /$\{segment}
        - id: company-service
          uri: lb://COMPANY-SERVICE
          predicates:
            - Path=/company-service/**
          filters:
            - RewritePath=/company-service/(?<segment>.*), /$\{segment}
      default-filters:
        - name: GlobalFilter
          args:
            baseMessage: Spring Cloud APIGateway Global Filter
            preLogger: true
            postLogger: true
      discovery:
        locator:
          enabled: true

# cloud server actuator
management:
  endpoints:
    web:
      exposure:
        include: refresh, health, beans, info
  endpoint:
    gateway:
      enabled: false #/actuator/gateway/routes 경로로 routes 보기

# 2시간(7,200,000), 1일(86,400,000) jwt token
token:
  access_expiration_time: 7200000
  refresh_expiration_time: 86400000
  secret-key: 'dGhpcy1pcy13b29yaW5wYW5nLXNlcnZpY2UtdGhpcy1pcy13b29yaW5wYW5nLXNlcnZpY2UtdGhpcy1pcy13b29yaW5wYW5nLXNlcnZpY2UtdGhpcy1pcy13b29yaW5wYW5nLXNlcnZpY2UtdGhpcy1pcy13b29yaW5wYW5nLXNlcnZpY2UtdGhpcy1pcy13b29yaW5wYW5nLXNlcnZpY2U='