server:
  port: 8000
  
spring:
  application:
    name: apigateway
  config:
    import: optional:configserver:http://localhost:8888/
    name: application
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user-service/**
          filters:
#            - RemoveRequestHeader-Cookie
            - RewritePath=/user-service/(?<segment>.*), /$\{segment}
      default-filters:
        - name: GlobalFilter
          args:
            preLogger: true
            postLogger: true
      discovery:
        locator:
          enabled: true

# cloud server actuator
management:
  endpoints:
    web:
      exposure:
        include: refresh, health, beans, info

messages:
  directory: ${user.dir}/workspace/github/woorinpang/attach/messages
