server:
  port: 8000

spring:
  application:
    name: apigateway
  config:
    import: optional:configserver:http://localhost:8888
    name: application
  cloud:
    gateway:
      routes:
        #user-service
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user-service/**
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/user-service/(?<segment>.*), /$\{segment}
        - id: store-service
          uri: lb://STORE-SERVICE
          predicates:
            - Path=/store-service/**
          filters:
            - RewritePath=/store-service/(?<segment>.*), /$\{segment}
        - id: order-service
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/order-service/**
          filters:
            - RewritePath=/order-service/(?<segment>.*), /$\{segment}
      default-filters:
        - name: GlobalFilter
          args:
            baseMessage: Spring Cloud APIGateway Global Filter
            preLogger: true
            postLogger: true
      discovery:
        locator:
          enabled: true

# cloud server actuator
management:
  endpoints:
    web:
      exposure:
        include: refresh, health, beans, info
  endpoint:
    gateway:
      enabled: false #/actuator/gateway/routes 경로로 routes 보기

apigateway:
  host: http://${apigateway.hostname:localhost}