server:
  port: 8000

spring:
  application:
    name: apigateway
  config:
    import: optional:configserver:http://localhost:8888
    name: application
  cloud:
    gateway:
      routes:
        #user-service
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user-service/**
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/user-service/(?<segment>.*), /$\{segment}
        - id: store-service
          uri: lb://STORE-SERVICE
          predicates:
            - Path=/store-service/**
          filters:
            - RewritePath=/store-service/(?<segment>.*), /$\{segment}
        - id: order-service
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/order-service/**
          filters:
            - RewritePath=/order-service/(?<segment>.*), /$\{segment}
        - id: company-service
          uri: lb://COMPANY-SERVICE
          predicates:
            - Path=/company-service/**
          filters:
            - RewritePath=/company-service/(?<segment>.*), /$\{segment}
      default-filters:
        - name: GlobalFilter
          args:
            baseMessage: Spring Cloud APIGateway Global Filter
            preLogger: true
            postLogger: true
      discovery:
        locator:
          enabled: true

# cloud server actuator
management:
  endpoints:
    web:
      exposure:
        include: refresh, health, beans, info
  endpoint:
    gateway:
      enabled: false #/actuator/gateway/routes 경로로 routes 보기


# 2시간(7,200,000), 1일(86,400,000) jwt token
#token:
#  access_expiration_time: 7200000
#  refresh_expiration_time: 86400000
#  secret-key: 'woorinpang_token_secret'
#
#eureka:
#  instance:
#    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}} # random port 사용시 eureka server에 인스턴스가 각각 표시되지 않는다
#    preferIpAddress: true # 서비스간 통신 시 hostname 보다 ip 를 우선
#  client:
#    register-with-eureka: true # eureka 서버에 등록
#    fetch-registry: true # 외부 검색 가능
#    service-url:
#      defaultZone: http://admin:admin@${eureka.instance.hostname:localhost}:8761/eureka
#
#apigateway:
#  host: http://${apigateway.hostname:localhost}